# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b0a435852b00d84d7b445bc8f98614926a9aab9b0e3f4a8c384519c4d65e8d325a89a31491ef4add2eb54410389e70d2016c2514a8cc82419e2e4066a1bbc6a

test:
  secret_key_base: 4550d58f1a1f201577a245c890cb0ce8e278e3fba70c131d6abbeaa9f06333fb37101a76776898f5ecca1163afdff6ff59f20a23c626c8c5dd5ad8295ef81d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
